# Generated by Django 6.0.1 on 2026-01-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
